### ISSUE TITLE
This product is very interesting but..

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [awsdocs/aws-panorama-developer-guide#1]
[Model compatibility list](https://github.com/awsdocs/aws-panorama-developer-guide/blob/main/resources/model-compatibility.md
)

Can u give more information about performance for each model?

Thank you.

**Comment by mwunderl** [comment]
Hi Cyl3el2Cleal2,

Thanks for your feedback. We're looking into providing performance information, but we don't have anything to share at this time.
