### ISSUE TITLE
Error in application SDK reference

### ISSUE THREAD

**Issue by mrtj** [awsdocs/aws-panorama-developer-guide#10]
The Media class documentation in the application SDK reference lists the arguments of the `add_label` method in `(x, y, text)` order:

https://github.com/awsdocs/aws-panorama-developer-guide/blob/b712d57cb7fbb3d45bf804b7c6f13f562902c781/resources/applicationsdk-reference.md?plain=1#L204

Instead, the correct argument order when calling this method is `(text, x, y)`, as it is correctly listed in the example of the same doc:

https://github.com/awsdocs/aws-panorama-developer-guide/blob/b712d57cb7fbb3d45bf804b7c6f13f562902c781/resources/applicationsdk-reference.md?plain=1#L270

If you can `add_label` with the wrong order of arguments, no type-checking is done on the python side, and your application will crash a very ugly C++ error like `terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_M_construct null not valid`, without any python call stack provided which makes debugging even harder.

**Comment by mwunderl** [comment]
Thanks Janos. I fixed the reference in [57c4870](https://github.com/awsdocs/aws-panorama-developer-guide/commit/57c4870ad2eeeab71c2d72a5bb1e1cf09d473131) and confirmed that the sample application uses the correct signature:
[aws-panorama-sample/packages/123456789012-SAMPLE_CODE-1.0/application.py#L125-L128](https://github.com/awsdocs/aws-panorama-developer-guide/blob/main/sample-apps/aws-panorama-sample/packages/123456789012-SAMPLE_CODE-1.0/application.py#L125-L128)
