### ISSUE TITLE
can I use own Jetson devkit

### ISSUE THREAD

**Issue by AndreV84** [awsdocs/aws-panorama-developer-guide#2]
@mwunderl 
can I use my own devkit?

**Comment by mwunderl** [comment]
Hi Andrey,

Thanks for your question. AWS Panorama supports only the AWS Panorama Appliance Developer Kit at this time.

**Comment by AndreV84** [comment]
@mwunderl 
Thank you for your response
so users with just AGX devkit are out of luck yet?
will it be possible to order the AWS panorama appliance developer kit using AWS cloud credits?

**Comment by mwunderl** [comment]
Yes, the software that runs Panorama applications is only available on the Panorama Appliance Developer Kit at this time. I will pass your feedback on to the service team, though. 

Regarding cloud credits, my understanding is that they are for service charges only, but you might pose the question in the forum: https://forums.aws.amazon.com/forum.jspa?forumID=388
