### ISSUE TITLE
how to pump streams into kvs?

### ISSUE THREAD

**Issue by mattfeury** [awsdocs/aws-panorama-developer-guide#6]
hello,

playing with these boxes and they look appealing. i'm noticing that the current architecture is more for processing things on a frame by frame basis. i'm interested in pumping data into KVS, but KVS only accepts h264/encoded stream data. This is normally very easy when i have an RTSP url because I can use the KVS gstreamer sink to just pipe them together. However, since i don't have access to the underlying URL (i can get stream_url but no credentials), i have to work with single image frames. 

is there a preferred approach to get data to pump into KVS for live view / playback?

thanks!

**Comment by mwunderl** [comment]
Hi mattfeury,

Thanks for your feedback. I've passed it on to the service team and they've added a feature request for KVS integration. Currently, the appliance does not output RTSP and you can only access individual frames of video within application code.

Thanks,
Michael at AWS
